[build]
entrypoint = "tmp/bin/gen"
cmd = "templ generate && go build -o tmp/bin/gen ./cmd"
args_bin = ["-serve"]
include_ext = ["go", "templ", "css", "js", "png", "jpg", "jpeg", "svg"]
exclude_regex = ["_templ\\.go"]
include_dir = ["static", "templates"]
delay = 100
send_interrupt = true

[log]
time = false
main_only = true
silent = true

[misc]
startup_banner = ""
