[tools]
go = "1.25.6"
air = "1.64.4"
"github:a-h/templ" = { version = "0.3.1020", exe = "templ" }

[tasks.build]
run = "templ generate && go run ./cmd"

[tasks.dev]
run = "air -c .air.toml"

[tasks.run]
run = "templ generate && go run ./cmd -serve"

[tasks.deploy]
run = "./deploy.sh"
