// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Head() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><title>Lytepage</title><!--\n\t\tmeta\n\t\t!--><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Lite yet powerful static side generator, using the power of go and templ\"><meta name=\"keywords\" content=\"go, templ, ssg, lytepage, static\"><meta name=\"author\" content=\"Péter Szarvas\"><!--\n\t\tcss reset: tailwindcss's preflight\n\t\thttps://github.com/tailwindlabs/tailwindcss/blob/3df38a7458cc2bc16eebc316e43f05db3c5d175b/packages/tailwindcss/preflight.css#L4\n\t\t--><link rel=\"stylesheet\" href=\"/static/preflight.css\"><!--\n\t\tgithub markdown css\n\t\thttps://github.com/sindresorhus/github-markdown-css\n\t\t--><link rel=\"stylesheet\" href=\"/static/markdown-light.css\"><link rel=\"stylesheet\" href=\"/static/markdown-dark.css\"><!--\n\t\tcode syntaxt highlighting: highlight.js \n\t\thttps://github.com/highlightjs/highlight.js\n\t\t--><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css\" media=\"(prefers-color-scheme: light)\"><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github-dark.min.css\" media=\"(prefers-color-scheme: dark), (prefers-color-scheme: no-preference)\"><script src=\"https://unpkg.com/@highlightjs/cdn-assets@11.9.0/highlight.min.js\"></script><!--\n\t\tcustom styles\n\t\t--><link rel=\"stylesheet\" href=\"/static/global.css\"><script>hljs.highlightAll();</script><!--\n\t\tGoogle programmable search engine - not in use - TODO do I need this?\n\t\t<script async src=\"https://cse.google.com/cse.js?cx=c769d03f1fdc04df5\"></script>\n\t\t<div class=\"gcse-search\"></div>\n\t\t-->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
